spring:
  application:
    name: ms-transfer

  datasource:
    url: jdbc:postgresql://autorack.proxy.rlwy.net:44391/railway
    username: postgres
    password: yeCelgbSVJEYDKjokUlvRhQDkxvqsMFx
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog.yaml
    enabled: true
    drop-first: false
    database-change-log-table: change_log
    database-change-log-lock-table: change_log_lock

server:
  port: 8082


application:
  security:
    secret-key: c2VjdXJlLXNlY3JldC1rZXktZm9yLUpXVC1lbmNyeXB0aW9uLTMyYnl0ZXM=
    jwt:
      expiration: 900000
      refresh-token:
        expiration: 86400000
